/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package idm;

import java.awt.Color;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Boody
 */
public class start_idm extends javax.swing.JFrame {

    /**
     * Creates new form start_
     */
  
   static int seq= 0;
   static public List<download> ob_download = new ArrayList<>();
  static  public  List<window_download> ob_window_download = new ArrayList<>();
  static  public  List<start_idm> ob_start= new ArrayList<>();
  String url="";
  String pass="";
   DefaultTableModel model_start_idm ;
    public start_idm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        jPanel1.setBackground(new Color(240,240,240));
       model_start_idm=(DefaultTableModel)jTable_start_idm.getModel();
      
    }
    
    void insert_table()
    {
        model_start_idm.addRow(new Object[]{seq,"ffff"});
    }
    
  public void set_url_pass(String u, String p)
   {
       url=u ;
       pass=p ;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_start_idm = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Pause All");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(700, 60, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Pause");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(620, 60, 40, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText(" All");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(560, 60, 40, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText(" All");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(410, 60, 40, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Capture.PNG"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 20, 58, 57);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/stop.PNG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(120, 20, 58, 57);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/resume.PNG"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(360, 20, 58, 57);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/resume.PNG"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(200, 20, 58, 57);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/stop all.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(280, 20, 58, 57);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/pause.PNG"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(700, 10, 50, 50);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/delete_All.PNG"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(520, 20, 58, 57);

        jTable_start_idm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seq_num", "Url", "Pass", "Size", "Status", "Transfer rate", "downloaded", "percent"
            }
        ));
        jTable_start_idm.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(jTable_start_idm);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 120, 1340, 540);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/delete.PNG"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(450, 20, 50, 57);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/pause.PNG"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(610, 10, 50, 50);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/redownload.PNG"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(800, 10, 50, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Redownload");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(790, 60, 80, 20);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/redownload.PNG"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(890, 10, 50, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Redownload All");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(890, 60, 100, 20);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        String url="http://localhost/sss.jpg";
//                //JOptionPane.showInputDialog(null, "Enter URL please ");
//        String pass="C:/Users/Boody/Desktop/photo_adel";
//                //JOptionPane.showInputDialog(null , "Enter the pass ");
   
           new get_url_pass().setVisible(true);
      //  model.addRow(new Object[]{seq,});
            
            
           
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int x=jTable_start_idm.getSelectedRow();
        if (x>-1)
        {
            ob_download.get((int)model_start_idm.getValueAt(x, 0)).flag_stop=true;
            ob_window_download.get((int)model_start_idm.getValueAt(x, 0)).setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int size=model_start_idm.getRowCount();
          for (int x= 0 ; x<size ; x++)
        {
            ob_download.get((int)model_start_idm.getValueAt(x, 0)).resumeThread();
          
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         int x=jTable_start_idm.getSelectedRow();
        if (x>-1)
        {
            ob_download.get((int)model_start_idm.getValueAt(x, 0)).resumeThread();
            ob_window_download.get((int)model_start_idm.getValueAt(x, 0)).jButton_pause.setText("Pause");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int size=model_start_idm.getRowCount();
       for (int x=0 ;x <size; x++)
        {
            ob_download.get((int)model_start_idm.getValueAt(x, 0)).flag_stop=true;
            ob_window_download.get((int)model_start_idm.getValueAt(x, 0)).setVisible(false);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int size=model_start_idm.getRowCount();
         for (int x= 0; x<size ; x++)
             {
            ob_download.get((int)model_start_idm.getValueAt(x, 0)).pauseThread();
          
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int size=model_start_idm.getRowCount();
          for (int x= 0 ; x<size ; x++)
              {
           // ob_download.get((int)model_start_idm.getValueAt(x, 0)).set_real_seq();
            ob_download.get((int)model_start_idm.getValueAt(x, 0)).flag_stop=true;
            ob_window_download.get((int)model_start_idm.getValueAt(x, 0)).setVisible(false);
            model_start_idm.removeRow(x);
          
        }
          
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         int x=jTable_start_idm.getSelectedRow();
        if (x>-1)
        {
            ob_download.get((int)model_start_idm.getValueAt(x, 0)).flag_stop=true;
            //ob_download.get((int)model_start_idm.getValueAt(x, 0)).set_real_seq();
            ob_window_download.get((int)model_start_idm.getValueAt(x, 0)).setVisible(false);
            model_start_idm.removeRow(x);
          ob_download.get((int)model_start_idm.getValueAt(x, 0)).set_real_seq();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         int x=jTable_start_idm.getSelectedRow();
        if (x>-1)
        {
            ob_download.get((int)model_start_idm.getValueAt(x, 0)).pauseThread();
           ob_window_download.get((int)model_start_idm.getValueAt(x, 0)).jButton_pause.setText("Resume");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         int x=jTable_start_idm.getSelectedRow();
        if (x>-1)
        {
           String urll= (String)model_start_idm.getValueAt(x, 1);
            String passss= (String)model_start_idm.getValueAt(x, 2);
          set_url_pass(urll, passss);
          download();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int size=model_start_idm.getRowCount();
        for (int x=0 ; x<size ; x++)
        {
           String urll= (String)model_start_idm.getValueAt(x, 1);
            String passss= (String)model_start_idm.getValueAt(x, 2);
          set_url_pass(urll, passss);
          download();
        }
    }//GEN-LAST:event_jButton12ActionPerformed
void download()
{
     window_download window=new window_download(seq);
             ob_window_download.add(window);
             window.setVisible(true);
                   
        
            download d=new download(url,pass,seq);
            ob_download.add(d);
           Thread t=new Thread(d);
           
                   
           t.start();
         //  model_start_idm.addRow(new Object[]{"lll"});
             seq++;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start_idm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start_idm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start_idm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start_idm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
              start_idm d=  new start_idm();d.setVisible(true);d.ob_start.add(d);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable_start_idm;
    // End of variables declaration//GEN-END:variables
}
